### ISSUE TITLE
Your GPU Spec for Training

### ISSUE THREAD

**Issue by riven314** [bearcatt/LaBERT#1]
Thanks for the great work!
In your paper, what are the GPU spec (e.g. GPU model, number of GPUs, and how many hours of training) for the training?

**Comment by bearcatt** [comment]
Thanks, our default setting uses 8 TITAN XP cards (12G memory) to get a batch size of 256. However, we found that a smaller batch size like 192 does not degrade the performance. We didn't try other batch sizes. 

The training time of our default setting is about 18 hours for 100k iterations, but we usually obtain the best validation performance between 50k and 70k iteration.

**Comment by riven314** [comment]
Thanks!
