### ISSUE TITLE
Refinement Steps

### ISSUE THREAD

**Issue by Eladhi** [bearcatt/LaBERT#10]
Hi,
Great work, thanks for sharing the code.

I could not find the number of refinement steps T in the configuration / code. Does it mean that this code is for autoregressive generation (table 1 instead of 2) only? If I'm mistaken, would you point the parameter that corresponds to T?

Thanks!

**Comment by bearcatt** [comment]
hi, it is [here ](https://github.com/bearcatt/LaBERT/blob/master/config.py#L31). The four values correspond to the refinement steps for 4 length-levels, respectively.
