### ISSUE TITLE
About datasets

### ISSUE THREAD

**Issue by zxh19976666** [bearcatt/LaBERT#12]
thanks for your job sir !  In this work,can i use myself datasets? thank you!

**Comment by bearcatt** [comment]
To use your own dataset, you need a pre-trained object detector to detect object proposals from the image and also extract their features. In our work, we use the features provided by [VLP](https://github.com/LuoweiZhou/VLP), which uses Faster RCNN pre-trained on MS COCO dataset as the feature extractor, and only the top100 proposals are used. To extract features for your own dataset, you can refer to the [tools](https://github.com/LuoweiZhou/detectron-vlp) provided by VLP.

**Comment by czy-orange** [comment]
> To use your own dataset, you need a pre-trained object detector to detect object proposals from the image and also extract their features. In our work, we use the features provided by [VLP](https://github.com/LuoweiZhou/VLP), which uses Faster RCNN pre-trained on MS COCO dataset as the feature extractor, and only the top100 proposals are used. To extract features for your own dataset, you can refer to the [tools](https://github.com/LuoweiZhou/detectron-vlp) provided by VLP.

@bearcatt In the paper, it's said Faster R-CNN is pretrained on Visual Genome dataset. Which one is right?

**Comment by zxh19976666** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
