### ISSUE TITLE
I can't download pre-trained weights

### ISSUE THREAD

**Issue by dXDb** [bearcatt/LaBERT#4]
baidu said "client of new version set up, but still can't download"
Can you send me e-mail these weights?
My e-mail is momakaka@naver.com

**Comment by bearcatt** [comment]
Hi, I've added Google Drive links for these models, you may download them from [here](https://github.com/bearcatt/LaBERT#data--pre-trained-models).

**Comment by dXDb** [comment]
Thanks! I love u!!!!!!!!!!!!!!!!!!!!!
