### ISSUE TITLE
Data Download Problem

### ISSUE THREAD

**Issue by tjuwyh** [bearcatt/LaBERT#6]
Hi, I am interested in your great work and wish to follow it in my further experiments but I have a problem when trying to download MSCOCO data. 
Since the one drive link provided in [VLP](https://github.com/LuoweiZhou/VLP#-data-preparation) cannot be visited in China without a VPN, it's difficult for me to prepare the data on my ubuntu machine.
Do you have any generous advice for me to solve this problem? Or would you please provide another download link that can be easily connected in China for MSCOCO data?
Thank you!

**Comment by bearcatt** [comment]
I'm going to back up the data on Baidu Cloud Disk. Once it is finished, I'll email you the link.

I've uploaded the data to Baidu disk, refer to [link](https://github.com/LuoweiZhou/VLP/issues/33#issuecomment-745111568)
