### ISSUE TITLE
MS COCO dataset download issue from the link provided [VLP github page]

### ISSUE THREAD

**Issue by SupragyaSonkar** [bearcatt/LaBERT#7]
Hey! Really interested in your work and would love to divulge in it more. 
I'm facing problems downloading the dataset. Can you please guide me as to where and how I can get the MS COCO dataset of 123k with splits of 113,287 images for training, 5,000 for validation, and 5,000 for offline evaluation?

The link provided for the dataset leads to the VLP github page. The dataset there is a combination of COCO and VQA of 95GB and 72GB. I'm unable to use them. Can you please suggest a way to download MS COCO dataset only.

**Comment by bearcatt** [comment]
VQA2.0 and COCO use the same images, so you can just use the data provided in the 95GB and 72GB packages.
