### ISSUE TITLE
id2captions_test.json file

### ISSUE THREAD

**Issue by saitarslanboun** [bearcatt/LaBERT#8]
Hi!

You do evaluation using data/id2captions_test.json and data/caption_results.json files. But I could not find out where the files are. Can you share the files with us?

Thanks,

**Comment by State226** [comment]
Do you find it?

**Comment by bearcatt** [comment]
t is automatically generated in the first run. See [here](https://github.com/bearcatt/LaBERT/blob/master/dataset.py#L54)

**Comment by State226** [comment]
> t is automatically generated in the first run. See [here](https://github.com/bearcatt/LaBERT/blob/master/dataset.py#L54)
Thanks
