### ISSUE TITLE
Missing key(s) in state_dict

### ISSUE THREAD

**Issue by zheng-xing** [bearcatt/LaBERT#9]
Hi,

Thanks for sharing this excellent work.
I encountered an issue when trying to test the inference step.
I downloaded the pretrained generator.pth and bert.pth from google drive.
The error message is attached below.
Could you give me an hint how to solve the problem?
Thanks in advance.

> Traceback (most recent call last):
>   File "inference.py", line 140, in <module>
>     g_checkpointer.load(config.model_path, True)
>   File "/data-2/home/xingzheng.xz/Research/LaBERT/utils/checkpointer.py", line 47, in load
>     self.model.load_state_dict(checkpoint.pop("model"))
>   File "/home/xingzheng.xz/miniconda3/envs/omninet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for Generator:
>         Missing key(s) in state_dict: "classifier.decoder.bias", "embedding_layer.position_ids".

**Comment by hjx999222** [comment]
Have you solved it? I have the same problem.

**Comment by zheng-xing** [comment]
> 

Hi I changed the following line in utils/checkpointer.py from 
                    self.model.load_state_dict(checkpoint.pop("model"))
to
                    self.model.load_state_dict(checkpoint.pop("model"), strict=False)

**Comment by hjx999222** [comment]
> 

Thank you
